services:
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ~/volumes/proxy/conf
        target: /etc/nginx/conf.d/
      - type: bind
        source: ~/volumes/proxy/certbot/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: ~/volumes/proxy/certbot/challenges
        target: /var/www/html/
    networks:
      - test-bridge

networks:
  test-bridge:
    external: true
