services:
  kanban_db:
    image: mariadb:11
    container_name: kanban_db
    environment:
      - MYSQL_ROOT_PASSWORD=${KANBAN_ROOT_DB}
      - MYSQL_USER=kanbaner
      - MYSQL_PASSWORD=${KANBAN_USER_DB}
      - MYSQL_DATABASE=kanban
    volumes:
      - type: bind
        source: ~/volumes/kanban/db
        target: /var/lib/mysql
    restart: unless-stopped
    networks:
      - kanban_network
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3

  kanban:
    image: leantime/leantime:3.4.7
    container_name: kanban
    restart: unless-stopped
    # Add security options
    security_opt:
      - no-new-privileges:true
    # Add capabilities
    cap_add:
      # - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
      - CAP_SETGID
      - CAP_SETUID
    #ports:
    #  - "${LEAN_PORT:-8080}:8080"
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
      - LEAN_PORT="8080"
      - LEAN_APP_URL=${PROTOCOL}://${KANBAN_HOST}.${DOMAIN}
      - LEAN_APP_DIR=""
      - LEAN_DEBUG=0
      
      - LEAN_DB_HOST=kanban_db
      - LEAN_DB_USER=kanbaner
      - LEAN_DB_PASSWORD=${KANBAN_USER_DB}
      - LEAN_DB_DATABASE=kanban
      - LEAN_DB_PORT=3306

      - LEAN_SESSION_PASSWORD=${KANBAN_SECRET_KEY}
      - LEAN_SESSION_EXPIRATION=86400
      - LEAN_SESSION_SECURE=TRUE
      
      - LEAN_SITENAME=Kanban board
      - LEAN_LANGUAGE=en-US
      - LEAN_DEFAULT_TIMEZONE=Europe/Warsaw
      # - LEAN_LOG_PATH=''
      - LEAN_DISABLE_LOGIN_PATH=FALSE
      
      - LEAN_LOGO_PATH=/dist/images/logo.svg
      - LEAN_PRINT_LOGO_URL=/dist/images/logo.png
      - LEAN_DEFAULT_THEME=default
      - LEAN_PRIMARY_COLOR=#006d9f
      - LEAN_SECONDARY_COLOR=#00a886

      - LEAN_USER_FILE_PATH=userfiles/
      - LEAN_DB_BACKUP_PATH=backupdb/

      - LEAN_USE_S3=FALSE
      # - LEAN_S3_KEY=''
      # - LEAN_S3_SECRET=''
      # - LEAN_S3_BUCKET=''
      # - LEAN_S3_USE_PATH_STYLE_ENDPOINT=false
      # - LEAN_S3_REGION=''
      # - LEAN_S3_FOLDER_NAME=''
      # - LEAN_S3_END_POINT=null

## Email
      - LEAN_EMAIL_RETURN=''
      - LEAN_EMAIL_USE_SMTP=false
      - LEAN_EMAIL_SMTP_HOSTS=''
      - LEAN_EMAIL_SMTP_AUTH=true
      - LEAN_EMAIL_SMTP_USERNAME=''
      - LEAN_EMAIL_SMTP_PASSWORD=''
      - LEAN_EMAIL_SMTP_AUTO_TLS=true
      - LEAN_EMAIL_SMTP_SECURE=''
      - LEAN_EMAIL_SMTP_SSLNOVERIFY=false
      - LEAN_EMAIL_SMTP_PORT=''

## LDAP
      - LEAN_LDAP_USE_LDAP=true
      - LEAN_LDAP_LDAP_DOMAIN=${LDAP_HOST}.${DOMAIN}
      - LEAN_LDAP_LDAP_TYPE=OL
      - LEAN_LDAP_HOST=ldap
      - LEAN_LDAP_PORT=3890
      # - LEAN_LDAP_URI=''
      - LEAN_LDAP_DN=ou=people,${LDAP_DOMAIN}
                                                   # Leantime->Ldap attribute mapping
      - LEAN_LDAP_KEYS={"username":"uid", "groups":"memberOf", "email":"mail", "firstname":"givenName", "lastname":"sn", "phone":"telephoneNumber", "jobTitle":"title", "jobLevel":"level", "department":"department" }

      - LEAN_LDAP_DEFAULT_ROLE_KEY=0

# Default role assignments upon first login.
# optional - Can be updated later in user settings for each user
      - LEAN_LDAP_GROUP_ASSIGNMENT={ \
          "5":{ \
                 "ltRole":"readonly", \
                 "ldapRole":"${KANBAN_READONLY}" \
               }, \
               "20":{ \
                 "ltRole":"editor", \
                  "ldapRole":"${KANBAN_USER}" \
               }, \
               "40":{ \
                 "ltRole":"admin", \
                  "ldapRole":"${KANBAN_ADMIN}" \
               }, \
          }
        # - LEAN_LDAP_GROUP_ASSIGNMENT={ \
        #   "5":{ \
        #          "ltRole":"readonly", \
        #          "ldapRole":"kanban_readonly" \
        #        }, \
        #        "10":{ \
        #          "ltRole":"commenter", \
        #           "ldapRole":"commenter" \
        #        }, \
        #        "20":{ \
        #          "ltRole":"editor", \
        #           "ldapRole":"editor" \
        #        }, \
        #        "30":{ \
        #          "ltRole":"manager", \
        #           "ldapRole":"manager" \
        #        }, \
        #        "40":{ \
        #          "ltRole":"admin", \
        #           "ldapRole":"administrators" \
        #        }, \
        #        "50":{ \
        #          "ltRole":"owner", \
        #          "ldapRole":"administrators" \
        #        } \
        #   }

## Redis (for session storage and cache)
      # - LEAN_USE_REDIS=false
      # - LEAN_REDIS_URL=''
      # - LEAN_REDIS_HOST=''
      # - LEAN_REDIS_PORT=6379
      # - LEAN_REDIS_PASSWORD=''
      # - LEAN_REDIS_SCHEME=''

## Rate limiting
      - LEAN_RATELIMIT_GENERAL=1000
      - LEAN_RATELIMIT_API=10
      - LEAN_RATELIMIT_AUTH=20

    networks:
      - kanban_network
      - test-bridge
    volumes:
      - type: bind
        source: ~/volumes/kanban/public
        target: /var/www/html/public/userfiles
      - type: bind
        source: ~/volumes/kanban/files
        target: /var/www/html/userfiles
      - type: bind
        source: ~/volumes/kanban/plugins
        target: /var/www/html/app/Plugins
      - type: bind
        source: ~/volumes/kanban/logs
        target: /var/www/html/storage/logs
    depends_on:
      - kanban_db
        # condition: service_healthy

  # Add a helper container for volume permissions
  # Run via docker compose --profile mysql_helper up -d
  # mysql_helper:
  #   image: mysql:8.4
  #   command: chown -R mysql:mysql /var/lib/mysql
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   user: root
  #   profiles: [ "helper" ]

# volumes:
#   db_data:
#   userfiles:                                               # New volume for public files
#   public_userfiles:
#   plugins:
#   logs:

networks:
  test-bridge:
    external: true
  kanban_network:
