x-environment:
  &default-back-environment
  # These environment variables will be used by taiga-back and taiga-async.
  # Database settings
  POSTGRES_DB: "kanban"
  POSTGRES_USER: "kabaner"
  POSTGRES_PASSWORD: "${KANBAN_USER_DB}"
  POSTGRES_HOST: "taiga-db"
  # Taiga settings
  TAIGA_SECRET_KEY: "${KANBAN_SECRET_KEY}"
  TAIGA_SITES_SCHEME: "${PROTOCOL}"
  TAIGA_SITES_DOMAIN: "${KANBAN_HOST}.${DOMAIN}"
  TAIGA_SUBPATH: ""
  # Email settings.
  EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend" # change 'console' to 'smtp' to allow mails to go
  DEFAULT_FROM_EMAIL: "admin@${KANBAN_HOST}.${DOMAIN}"
  EMAIL_USE_TLS: "FALSE"
  EMAIL_USE_SSL: "FALSE"
  EMAIL_HOST: "${SMTP_HOST}.${DOMAIN}"
  EMAIL_PORT: "587"
  EMAIL_HOST_USER: "mailer"
  EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
  # Rabbitmq settings
  RABBITMQ_USER: "kanbaner"
  RABBITMQ_PASS: "${KANBAN_RABBITMQ_PASS}"
  # Telemetry settings
  ENABLE_TELEMETRY: FALSE
  # ...your customizations go here

x-volumes:
  &default-back-volumes
  # These volumens will be used by taiga-back and taiga-async.
  # - taiga-static-data:/taiga-back/static
  # - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py
  - type: bind
    source: ~/volumes/kanban/media
    target: /taiga-back/media
  - type: bind
    source: ~/volumes/kanban/static
    target: /taiga-back/static


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: "kanban"
      POSTGRES_USER: "kabaner"
      POSTGRES_PASSWORD: "${KANBAN_USER_DB}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanbaner"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s      
    volumes:
      - type: bind
        source: ~/volumes/kanban/db
        target: /var/lib/postgresql/data
    networks:
      - kanban

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - kanban
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - kanban
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${KANBAN_MQ_COOKIE}"
      RABBITMQ_DEFAULT_USER: "kanbaner"
      RABBITMQ_DEFAULT_PASS: "${KANBAN_RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-async-rabbitmq"
    volumes:
      - type: bind
        source: ~/volumes/kanban/rabbit-mq
        target: /var/lib/rabbitmq-async
    networks:
      - kanban

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "${PROTOCOL}://${KANBAN_HOST}.${DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "${WEBSOCKET_PROTOCOL}://${KANBAN_HOST}.${DOMAIN}"
      TAIGA_SUBPATH: ""
      # ...your customizations go here
    networks:
      - kanban
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: "kanbaner"
      RABBITMQ_PASS: "${KANBAN_RABBITMQ_PASS}"
      TAIGA_SECRET_KEY: "${KANBAN_SECRET_KEY}"
    networks:
      - kanban
    depends_on:
      taiga-events-rabbitmq:
        condition: service_started

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${KANBAN_MQ_COOKIE}"
      RABBITMQ_DEFAULT_USER: "kanbaner"
      RABBITMQ_DEFAULT_PASS: "${KANBAN_RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - type: bind
        source: ~/volumes/kanban/rabbit-mq
        target: /var/lib/rabbitmq-events
    networks:
      - kanban

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "15724800"
      SECRET_KEY: "${KANBAN_SECRET_KEY}"
    networks:
      - kanban

  kanban_proxy:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - type: bind
        source: ~/volumes/kanban/media
        target: /taiga-back/media
      - type: bind
        source: ~/volumes/kanban/static
        target: /taiga-back/static

    networks:
      - kanban
      - test-bridge
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

networks:
  test-bridge:
    external: true
  kanban:
