services:
  fileshare:
    networks:
      - test-bridge
      - fileshare-network
    image: nextcloud:31
#    build:
#      context: fileshare
#      args:
#        - LDAP_DOMAIN=${LDAP_DOMAIN}
#        - LDAP_PASS=${LDAP_PASS}
    container_name: fileshare
    restart: always
    ports:
      - "8888:80"
    environment:
#      - PUID=${USER_UID}
#      - PGID=${USER_GID}
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${FILESHARE_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${FILESHARE_HOST}.${DOMAIN}
      # - NEXTCLOUD_DB_HOST=fileshare_db
      - MYSQL_HOST=fileshare_db
      - MYSQL_USER=clouder
      - MYSQL_PASSWORD=${FILESHARE_USER_DB}
      - MYSQL_DATABASE=nextcloud
#      - PHP_MEMORY_LIMIT=2048M
    volumes:
      - fileshare-data:/var/www/html/data
      - fileshare-apps:/var/www/html/apps
      - fileshare-custom-apps:/var/www/html/custom-apps
      - fileshare-config:/var/www/html/config
      - fileshare-application:/var/www/html

#      - type: bind
#        source: ~/volumes/fileshare/data
#        target: /var/www/html/data
#      - type: bind
#        source: ~/volumes/fileshare/apps
#        target: /var/www/html/apps
#      - type: bind
#        source: ~/volumes/fileshare/custom-apps
#        target: /var/www/html/custom-apps
#      - type: bind
#        source: ~/volumes/fileshare/config
#        target: /var/www/html/config
#      - type: bind
#        source: ~/volumes/fileshare/application
#        target: /var/www/html

      # - type: bind
#     #   source: ~/volumes/#fileshare/hooks/pre-installation
      #   target: /docker-entrypoint-hooks.d/pre-installation
      # - type: bind
      #   source: ~/volumes/fileshare/hooks/post-installation
      #   target: /docker-entrypoint-hooks.d/post-installation
      # - type: bind
      #   source: ~/volumes/fileshare/hooks/pre-upgrade
      #   target: /docker-entrypoint-hooks.d/pre-upgrade
      # - type: bind
      #   source: ~/volumes/fileshare/hooks/post-upgrade
      #   target: /docker-entrypoint-hooks.d/post-upgrade
      # - type: bind
      #   source: ~/volumes/fileshare/hooks/before-starting
      #   target: /docker-entrypoint-hooks.d/before-starting





        #add hooks!
    # volumes:
      # - ./app-hooks/pre-installation:/docker-entrypoint-hooks.d/pre-installation
      # - ./app-hooks/post-installation:/docker-entrypoint-hooks.d/post-installation
      # - ./app-hooks/pre-upgrade:/docker-entrypoint-hooks.d/pre-upgrade
      # - ./app-hooks/post-upgrade:/docker-entrypoint-hooks.d/post-upgrade
      # - ./app-hooks/before-starting:/docker-entrypoint-hooks.d/before-starting

    depends_on:
      - fileshare_db

  fileshare_db:
    networks:
      - fileshare-network
    image: mariadb:11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${FILESHARE_ROOT_DB}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=clouder
      - MYSQL_PASSWORD=${FILESHARE_USER_DB}
    volumes:
      - type: bind
        source: ~/volumes/fileshare/db
        target: /var/lib/mysql

        #todo: add officera ??


networks:
  test-bridge:
    external: true
  fileshare-network:
    driver: bridge
volumes:
  fileshare-data:
    name: "fileshare-data"
  fileshare-apps:
    name: "fileshare-apps"
  fileshare-custom-apps:
    name: "fileshare-custom-apps"
  fileshare-config: 
    name: "fileshare-config"
  fileshare-application:
    name: "fileshare-application"
 
