services:
  fileshare:
    networks:
      - test-bridge
      - fileshare-network
    image: owncloud/server:10
    container_name: fileshare
    restart: always
    # ports:
    #   - "8888:8080"
    environment:
      OWNCLOUD_ADMIN_USERNAME: admin
      OWNCLOUD_ADMIN_PASSWORD:       # onlyoffice # richdocuments
      OWNCLOUD_APPS_INSTALL: 'gallery, user_ldap, customgroups, impersonate, web'
      OWNCLOUD_DB_HOST: fileshare_db
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: root
      OWNCLOUD_DB_PASSWORD: JvÏªPæñÚËWE¤îÈaÊfWkÝÐÊO·3öñã¶IÔebmºËê8µJ°1YÒLlzpäÜOC¬Lð
      OWNCLOUD_DB_TYPE: mysql
      # OWNCLOUD_DOMAIN: file.test
      OWNCLOUD_TRUSTED_DOMAINS: ""

    volumes:
      - type: bind
        source: ~/volumes/fileshare/data
        target: /mnt/data
    depends_on:
      - fileshare_db


  fileshare_db:
    networks:
      - fileshare-network
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=    
      - MYSQL_DATABASE=
      # - MYSQL_USER=nextclouder
      # - MYSQL_PASSWORD=secret-pass
    volumes:
      - type: bind
        source: ~/volumes/fileshare/db
        target: /var/lib/mysql


  # fileshare_db:
  #   networks:
  #     - fileshare-network
  #   image: mysql:8
  #   restart: always
  #   # ports:
  #   #  - "22137:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: JvÏªPæñÚËWE¤îÈaÊfWkÝÐÊO·3öñã¶IÔebmºËê8µJ°1YÒLlzpäÜOC¬Lð
  #     # MYSQL_USER: kurniker
  #     # MYSQL_PASSWORD: 7OUvcg4v5b6SY1t7KaKNSlXiJaNN42puDKehkHdEt2zeLmxv
  #     MYSQL_DATABASE: owncloud
  #   volumes:
  #     - type: bind
  #       source: ~/volumes/fileshare/db
  #       target: /var/lib/mysql

  # office_suite:
  #   networks:
  #     - fileshare-network
  #   image: collabora/code:latest
  #   restart: always
  #   ports:
  #    - "9980:9980"
    # environment:
    #   - domain=localhost
#      - DONT_GEN_SSL_CERT=true
#    cap_add:
#      - MKNOD

networks:
  test-bridge:
    external: true
  fileshare-network:
    driver: bridge
