services:
  fileshare:
    image: owncloud/server:10
    restart: always
    ports:
      - "8888:8080"
    environment:
      name: value
    volumes:
      - type: bind
        source: ~/volumes/fileshare/
        target: /mnt/data
  #  depends_on:
  #    - fileshare_db
  #fileshare_db:
  #  image: mariadb:11
  #  restart: always

